import os
from dotenv import load_dotenv

load_dotenv()

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
OPENWEATHER_API_KEY = os.getenv("OPENWEATHER_API_KEY")
GOOGLE_PLACES_API_KEY = os.getenv("GOOGLE_PLACES_API_KEY")
ELEVENLABS_API_KEY = os.getenv("ELEVENLABS_API_KEY")
ELEVENLABS_VOICE_ID = os.getenv("ELEVENLABS_VOICE_ID", "pNInz6obpgDQGcFmaJgB")  # Adam
MODEL = "claude-sonnet-4-6"

# FMCSA HOS limits
DRIVE_LIMIT_HOURS = 11
ON_DUTY_LIMIT_HOURS = 14
BREAK_TRIGGER_HOURS = 8
BREAK_DURATION_MINUTES = 30
WEEKLY_LIMIT_HOURS = 70
WEEKLY_PERIOD_DAYS = 8
RESET_HOURS = 10

# Proactive timing
ROUTE_BRIEFING_INTERVAL_MIN = 45
WELLNESS_CHECKIN_INTERVAL_MIN = 120
